# Generated by Django 3.2 on 2021-04-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Your book's name", max_length=200, verbose_name='Book Name')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text="Your book's link(will auto generated)", max_length=300, unique=True, verbose_name='Book Link')),
                ('cover', models.ImageField(help_text="Your book's cover for showing", upload_to='BookCovers', verbose_name='Book Cover')),
                ('description', models.TextField(help_text="Your book's details", verbose_name='Book Details')),
                ('book_status', models.CharField(blank=True, choices=[('dr', 'Draft'), ('se', 'Sent')], help_text="Your book's status", max_length=2, verbose_name='Book Status')),
                ('publish_date', models.DateTimeField(blank=True, help_text="Your book's publish date", verbose_name='Book Publish Date')),
                ('is_plus', models.BooleanField(default=False, help_text='Is book for plus members?', verbose_name='Is plus')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offically Book',
                'verbose_name_plural': 'Offically Books',
            },
        ),
    ]
